"""
Training script to train the glucose prediction model with generated data.

This script reads the training data generated by prepare_glucose_training_data.ts
and sends it to the PredictiveModelsService API for training.

Usage:
    python scripts/train_glucose_model.py --data glucose_training_data.json
"""

import argparse
import json
import requests
from pathlib import Path
from typing import Dict, Any


def load_training_data(file_path: str) -> Dict[str, Any]:
    """Load training data from JSON file."""
    with open(file_path, 'r') as f:
        data = json.load(f)
    return data


def train_model(
    api_url: str,
    model_name: str,
    training_data: Dict[str, Any],
    test_size: float = 0.2,
    parameters: Dict[str, Any] = None
) -> Dict[str, Any]:
    """
    Train glucose prediction model via API.
    
    Args:
        api_url: Base URL of PredictiveModelsService
        model_name: Name for the trained model
        training_data: Training data from generator
        test_size: Fraction for validation (0.0-0.5)
        parameters: XGBoost hyperparameters
        
    Returns:
        Training response with metrics
    """
    # Extract samples
    samples = training_data.get('samples', [])
    
    if len(samples) == 0:
        raise ValueError("No training samples found in data file")
    
    # Format for API
    formatted_samples = []
    for sample in samples:
        formatted_samples.append({
            'status_history': sample['status_history'],
            'actual_glucose_60min': sample['actual_glucose_60min']
        })
    
    # Prepare request
    request_data = {
        'model_name': model_name,
        'samples': formatted_samples,
        'test_size': test_size,
        'parameters': parameters or {}
    }
    
    # Send training request
    endpoint = f"{api_url}/api/v1/train/glucose"
    print(f"Training model '{model_name}' with {len(formatted_samples)} samples...")
    print(f"Endpoint: {endpoint}")
    
    response = requests.post(
        endpoint,
        json=request_data,
        headers={'Content-Type': 'application/json'}
    )
    
    if response.status_code != 201:
        raise Exception(f"Training failed: {response.status_code} - {response.text}")
    
    return response.json()


def main():
    parser = argparse.ArgumentParser(
        description='Train glucose prediction model with generated training data'
    )
    parser.add_argument(
        '--data',
        type=str,
        default='glucose_training_data.json',
        help='Path to training data JSON file'
    )
    parser.add_argument(
        '--model-name',
        type=str,
        default='glucose_predictor_v1',
        help='Name for the trained model'
    )
    parser.add_argument(
        '--api-url',
        type=str,
        default='http://localhost:8000',
        help='Base URL of PredictiveModelsService API'
    )
    parser.add_argument(
        '--test-size',
        type=float,
        default=0.2,
        help='Fraction of data for validation (0.0-0.5)'
    )
    parser.add_argument(
        '--max-depth',
        type=int,
        default=6,
        help='XGBoost max_depth parameter'
    )
    parser.add_argument(
        '--n-estimators',
        type=int,
        default=100,
        help='XGBoost n_estimators parameter'
    )
    parser.add_argument(
        '--learning-rate',
        type=float,
        default=0.1,
        help='XGBoost learning_rate parameter'
    )
    
    args = parser.parse_args()
    
    # Load training data
    print(f"Loading training data from: {args.data}")
    training_data = load_training_data(args.data)
    
    print(f"Loaded {len(training_data.get('samples', []))} samples")
    print(f"Generated at: {training_data.get('generated_at')}")
    print(f"Summary: {training_data.get('summary')}")
    
    # Prepare XGBoost parameters
    parameters = {
        'max_depth': args.max_depth,
        'n_estimators': args.n_estimators,
        'learning_rate': args.learning_rate
    }
    
    # Train model
    try:
        result = train_model(
            api_url=args.api_url,
            model_name=args.model_name,
            training_data=training_data,
            test_size=args.test_size,
            parameters=parameters
        )
        
        print("\n=== Training Complete ===")
        print(f"Model: {result['model_name']}")
        print(f"Status: {result['status']}")
        print(f"Message: {result['message']}")
        print(f"\nMetrics:")
        for metric, value in result['metrics'].items():
            print(f"  {metric}: {value:.4f}")
        
        print(f"\nTop 5 Features by Importance:")
        feature_imp = result.get('feature_importance', {})
        sorted_features = sorted(feature_imp.items(), key=lambda x: x[1], reverse=True)
        for feature, importance in sorted_features[:5]:
            print(f"  {feature}: {importance:.4f}")
        
        print(f"\nModel saved as: {result['model_name']}")
        print(f"Trained at: {result['trained_at']}")
        
    except Exception as e:
        print(f"\n❌ Training failed: {str(e)}")
        return 1
    
    return 0


if __name__ == '__main__':
    exit(main())
